### ISSUE TITLE
what repository to use

### ISSUE THREAD

**Issue by thijstriemstra** [lightninglabs/lightning-coindesk#4]
The docs (https://github.com/lightninglabs/lightning-coindesk#setup) point to a different repository than this one:

```
git clone https://github.com/MaxFangX/lightning-coindesk
cd lightning-coindesk
```

Is this a typo, which one should I use?

**Comment by thijstriemstra** [comment]
ping @MaxFangX

**Comment by MaxFangX** [comment]
They link to the same resource on Github - the repo was moved to the lightninglabs org but both links will work. Closing

**Comment by thijstriemstra** [comment]
ping @MaxFangX
